[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "piwobblyware"
version = "0.0.1"
dependencies = [
    "opencv-python",
    "numpy",
    "matplotlib",
]

[tool.setuptools]
packages = ["panic.controller"]
package-dir = {"panic.controller" = "src"}
